---
Name: deployment_schedule_routes
After:
    - "framework/*"
---
SilverStripe\Control\Director:
    rules:
        "deployment-schedule//$Action/$ID/$OtherID": WebbuildersGroup\DeploymentNotes\Control\DeploymentSchedule